image: Visual Studio 2017

build_script:
  - git clone %CLONE_URL% proj
  - cd proj
  - git submodule update --init --recursive
  - mkdir win64
  - cd win64
  - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" ..
  - msbuild huge.sln /t:Build /p:Configuration=Release
  - dir Release
  - cd ..
  - mkdir win32
  - cd win32
  - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017" ..
  - msbuild huge.sln /t:Build /p:Configuration=Release
  - dir Release

artifacts:
  - path: 'proj\win32\Release\*.exe'
    name: build32
  - path: 'proj\win64\Release\*.exe'
    name: build64
